### ISSUE TITLE
round(): Argument #1 ($num) must be of type int|float, string given

### ISSUE THREAD

**Issue by jjuszkiewicz** [nokaut/api-kit#8]
A api-key has problem with  PHP 8: `round(): Argument #1 ($num) must be of type int|float, string given`, file: https://github.com/nokaut/api-kit/blob/master/src/ClientApi/Rest/RestClientApi.php#L388

The problem is caused by cast to string `$runTime = (string)$response->getHeaderLine('X-Runtime');`:
https://github.com/nokaut/api-kit/blob/master/src/ClientApi/Rest/RestClientApi.php#L385

**Comment by dwilkiewicz** [comment]
Fixed in [v1.8.1](https://github.com/nokaut/api-kit/releases/tag/v1.8.1)
